Map<int, String> numbers = {
  1: "KIN-IN-NI",
  2: "KEJI",
  3: "KETA",
  4: "KERIN",
  5: "KARUN",
  6: "KEFA",
  7: "KEJE",
  8: "KEJO",
  9: "KESAN",
  10: "KEWA",
  11: "KOKANLA",
  12: "KEJILA",
  13: "KETALA",
  14: "KERINLA",
  15: "KEEDOGUN",
  16: "KERINDINLOGUN",
  17: "KETADINLOGUN",
  18: "KEJIDINLOGUN",
  19: "KOKANDINLOGUN",
  20: "OGUN",
};
