/// Flutter icons CACSAIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CACSAIcons
///      fonts:
///       - asset: fonts/CACSAIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CACSAIcons {
  CACSAIcons._();

  static const _kFontFam = 'CACSAIcons';
  static const String? _kFontPkg = null;

  static const IconData backwardnormal = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarbold = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarnormal = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closenormal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardbold = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dailyworkbold = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homenormal = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homebold = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copynormal = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forwardnormal = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infobold = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationbold = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manualbold = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mediabold = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationbold = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationnormal = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seenormal = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsbold = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
